### PR TITLE
Get rid off annoying mails & fix a heading

### PR DESCRIPTION
**Pull request by arstrube**

### CODE REVIEW

**Comment by basvodde** [comment]
You didn't need to replace it with something?

**Comment by arstrube** [comment]
Nope. There is no sense in specifying somthing where (apparently) there is no choice. The site looks just the same as before at http://arstrube.github.io.

**Comment by basvodde** [comment]
Sure? Feels odd to have no replacement :)

**Comment by arstrube** [comment]
It's a simplification of the very complex _config.yml :p

**Comment by arstrube** [comment]
We could comment it to show how it is done, in case there'll ever be a different choice than `rouge`. Or perhaps you know something prettier? That would make me feel better about leaving it in........

**Comment by basvodde** [comment]
Ok.

**Comment by arstrube** [comment]
Actually, from what I understand, it's a plugin, not a color scheme. It's the default, and they kind of threw out Pygments.

**Pull request merged**
